spring.application.name=ms-recargas
server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/paygo_recargas
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
tarjetas.service.url=http://localhost:8081
