spring.application.name=ms-recargas
server.port=8082
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/paygo_recargas}
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.kafka.bootstrap-servers=${KAFKA_BOOT:localhost:9092}
app.messaging.mode=both
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASS:guest}
tarjetas.service.url=${TARJETAS_URL:http://localhost:8081}
